services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./create_expenses_table.sql:/docker-entrypoint-initdb.d/create_expenses_table.sql # Automatically create the expenses table on startup

  backend:
    build: ./backend/python
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: expense_db
      DB_USER: expense_user
      DB_PASSWORD: expense_pass
    ports:
      - "50051:50051"
    working_dir: /app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8081:80" # Serve Nginx on port 8081
    working_dir: /app

  envoy:
    image: envoyproxy/envoy:v1.33-latest
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - backend

volumes:
  db_data: