# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import expense_pb2 as expense__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in expense_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExpenseTrackerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListExpenses = channel.unary_unary(
                '/ExpenseTracker/ListExpenses',
                request_serializer=expense__pb2.ListExpensesRequest.SerializeToString,
                response_deserializer=expense__pb2.ListExpensesResponse.FromString,
                _registered_method=True)
        self.AddExpenses = channel.unary_unary(
                '/ExpenseTracker/AddExpenses',
                request_serializer=expense__pb2.CreateExpensesRequest.SerializeToString,
                response_deserializer=expense__pb2.CreateExpensesResponse.FromString,
                _registered_method=True)
        self.DeleteExpenses = channel.unary_unary(
                '/ExpenseTracker/DeleteExpenses',
                request_serializer=expense__pb2.DeleteExpensesRequest.SerializeToString,
                response_deserializer=expense__pb2.DeleteExpensesResponse.FromString,
                _registered_method=True)
        self.UpdateExpenses = channel.unary_unary(
                '/ExpenseTracker/UpdateExpenses',
                request_serializer=expense__pb2.UpdateExpensesRequest.SerializeToString,
                response_deserializer=expense__pb2.UpdateExpensesResponse.FromString,
                _registered_method=True)
        self.GetSummary = channel.unary_unary(
                '/ExpenseTracker/GetSummary',
                request_serializer=expense__pb2.GetSummaryRequest.SerializeToString,
                response_deserializer=expense__pb2.GetSummaryResponse.FromString,
                _registered_method=True)


class ExpenseTrackerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListExpenses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddExpenses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteExpenses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateExpenses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExpenseTrackerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListExpenses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExpenses,
                    request_deserializer=expense__pb2.ListExpensesRequest.FromString,
                    response_serializer=expense__pb2.ListExpensesResponse.SerializeToString,
            ),
            'AddExpenses': grpc.unary_unary_rpc_method_handler(
                    servicer.AddExpenses,
                    request_deserializer=expense__pb2.CreateExpensesRequest.FromString,
                    response_serializer=expense__pb2.CreateExpensesResponse.SerializeToString,
            ),
            'DeleteExpenses': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteExpenses,
                    request_deserializer=expense__pb2.DeleteExpensesRequest.FromString,
                    response_serializer=expense__pb2.DeleteExpensesResponse.SerializeToString,
            ),
            'UpdateExpenses': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateExpenses,
                    request_deserializer=expense__pb2.UpdateExpensesRequest.FromString,
                    response_serializer=expense__pb2.UpdateExpensesResponse.SerializeToString,
            ),
            'GetSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSummary,
                    request_deserializer=expense__pb2.GetSummaryRequest.FromString,
                    response_serializer=expense__pb2.GetSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ExpenseTracker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ExpenseTracker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExpenseTracker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListExpenses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExpenseTracker/ListExpenses',
            expense__pb2.ListExpensesRequest.SerializeToString,
            expense__pb2.ListExpensesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddExpenses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExpenseTracker/AddExpenses',
            expense__pb2.CreateExpensesRequest.SerializeToString,
            expense__pb2.CreateExpensesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteExpenses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExpenseTracker/DeleteExpenses',
            expense__pb2.DeleteExpensesRequest.SerializeToString,
            expense__pb2.DeleteExpensesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateExpenses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExpenseTracker/UpdateExpenses',
            expense__pb2.UpdateExpensesRequest.SerializeToString,
            expense__pb2.UpdateExpensesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExpenseTracker/GetSummary',
            expense__pb2.GetSummaryRequest.SerializeToString,
            expense__pb2.GetSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
